[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CreationMRFprofiles"
authors = [{name = "Layla Hirsh", email = "lhirsh@pucp.edu.pe"}]
dynamic = ["version", "description"]
